### ISSUE TITLE
Opdatering med SL2022 logo

### ISSUE THREAD

**Issue by BueHeckmann** [Spejderneslejr/spejderneslejrdk#118]
Så har vi fået lavet vores endelige logo for SL2022 - kan vi indsætte det på den opdaterede hjemmeside? Jeg har desuden vedhæftet Hedelands logo, som meget gerne må stå til venstre for SL-logoet (der hvor Sønderborgs logo var oprindeligt)

![HedelandNaturpark](https://user-images.githubusercontent.com/69456056/91168596-2ec0d280-e6d6-11ea-9c5d-3058b89b7b4a.JPG)
![Spejdernes Lejr 2022_LOGO_Sekundær](https://user-images.githubusercontent.com/69456056/91168547-1c469900-e6d6-11ea-824b-3751b046ac68.png)
![Spejdernes Lejr 2022_LOGO_Primær](https://user-images.githubusercontent.com/69456056/91168561-1fda2000-e6d6-11ea-81c3-74b0cf31fcf7.png)

**Comment by danquah** [comment]
Check, jeg tager en omgang i aften og vender tilbage.

**Comment by danquah** [comment]
@BueHeckmann kan du klare 2022 versionen af det her: https://spejderneslejr.dk/themes/custom/camp/svg/logo.svg i SVG?

**Comment by danquah** [comment]
Jeg har lavet min egen konvertering og lagt på http://pr-107-puszisi-kigwipdp3tsiq.eu-4.platformsh.site/ - men det står ikke helt så skarpt som hvis det kan blive eksporteret fra originalen.
