### ISSUE TITLE
Udskiftning af logo i bevægelig menu

### ISSUE THREAD

**Issue by BueHeckmann** [Spejderneslejr/spejderneslejrdk#123]
Når man på forsiden scroller nedad, så begynder menuen at bevæge sig med i toppen. Den bevægelige menu har SL2017 logo ude i venstre side. Kan den erstattes med det vedhæftede logo?
![Spejdernes Lejr 2022_LOGO_Sekundær](https://user-images.githubusercontent.com/69456056/92598941-d7139100-f2a9-11ea-84a9-20aa1af79eef.png)

[2022_LOGOer.zip](https://github.com/sl2017/spejderneslejrdk/files/5237927/2022_LOGOer.zip)
Kan du bruge et af disse i zip filen - ellers kan du måske også få adgang til dem her https://korpskontoret.sharepoint.com/:f:/s/SL2022Kommunikation/EpGLl6W5tY1Lps264rR3bHkBZikUpL6g5Fr9acRrPLFJuw?e=MLRhj7

**Comment by danquah** [comment]
@BueHeckmann jep, er det muligt at få den (og hovedlogoet) i svg?

**Comment by BueHeckmann** [comment]
Det prøver jeg at skaffe - men det tager nok lidt tid, da jeg lige skal have fat i grafikeren.

**Comment by danquah** [comment]
@BueHeckmann ok, nu kommer jeg liiige så langsomt igang igen - jeg har startet med at få fikset logoet i menuen

**Comment by BueHeckmann** [comment]
det ser godt ud!  Jeg er også først tilbage på pinden fra i dag - nu som far til en lille søn :)

**Comment by danquah** [comment]
Skønt, og tillykke!
