### ISSUE TITLE
Menuen forsvinder på undersider

### ISSUE THREAD

**Issue by BueHeckmann** [Spejderneslejr/spejderneslejrdk#124]
Efter at vi har (genaktiveret) siden, kan jeg se, at menuen forsvinder, når man er inder på undersiderne - kan menuen gøres synlig på undersiderne også?

**Comment by danquah** [comment]
Jeg prøver at få kikket på det hen over weekenden.

**Comment by danquah** [comment]
og det bliver i aften - til gengæld har jeg helt sikkert et par timer til det så det burde kunne være tæt på sikkert at jeg får set påd et

**Comment by danquah** [comment]
@BueHeckmann jeg kan ikke reproducere denne - mit bedste gæt var at du så en gammel version af siden?

**Comment by BueHeckmann** [comment]
Jeps, tror du har ret. Nu gør den i hvert fald det rigtige.
