### ISSUE TITLE
Opdatering af Hedeland logo i header

### ISSUE THREAD

**Issue by BueHeckmann** [Spejderneslejr/spejderneslejrdk#130]
Hej Mads, så er det endelig lykkedes mig at få Hedelands rigtige logo (og ikke blot et billede af det) - kan du erstatte det nuværende på hjemmesidens header med et af de vedhæftede?
![Hedeland Naturpark - cmyk JPG (002)](https://user-images.githubusercontent.com/69456056/99679463-452fbd80-2a7c-11eb-8f7c-407f4026a5b0.JPG)
![Hedeland Naturpark - cmyk PNG (002)](https://user-images.githubusercontent.com/69456056/99679469-4660ea80-2a7c-11eb-9614-5ea7ed500691.PNG)

**Comment by danquah** [comment]
Fedt, jeg giver det et kik i aften!
